import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { reportStructure } from './report-structure.ts'

const root = resolve(import.meta.dirname, '..')

/** Write one file under the fixture root, creating its parent directories. */
function write(fixture: string, path: string, content: string): void {
  const full = join(fixture, path)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content)
}

/** A function declaration spanning `lines` lines, closing brace included. */
function longFunction(name: string, lines: number): string {
  const body = Array.from({ length: lines - 2 }, (_, index) => `  const v${String(index)} = ${String(index)}`)
  return `export function ${name}(): void {\n${body.join('\n')}\n}\n`
}

/** A file of `lines` comment lines, with an optional generated banner. */
function filler(lines: number, generated: boolean): string {
  const head = generated ? ['// Generated by scripts/probe.ts — do not edit.'] : ['// Probe file.']
  return [...head, ...Array.from({ length: lines - head.length }, () => '// filler')].join('\n') + '\n'
}

const fixtures: string[] = []
afterEach(() => {
  for (const fixture of fixtures.splice(0)) rmSync(fixture, { recursive: true, force: true })
})

function fixtureRoot(): string {
  const fixture = mkdtempSync(join(tmpdir(), 'dsh-report-structure-'))
  fixtures.push(fixture)
  return fixture
}

describe('reportStructure', () => {
  it('counts a declaration that spans more than 150 lines and ignores a shorter one', () => {
    const fixture = fixtureRoot()
    write(fixture, 'packages/a/b/src/big.ts', longFunction('big', 151) + longFunction('small', 20))
    const report = reportStructure(fixture)
    expect(report.longFunctions.map(entry => entry.name)).toEqual(['big'])
    expect(report.longFunctions[0]).toEqual({ path: 'packages/a/b/src/big.ts', line: 1, name: 'big', lines: 151 })
  })

  it('skips test files and names them in the scan', () => {
    const fixture = fixtureRoot()
    write(fixture, 'packages/a/b/src/big.ts', longFunction('big', 151))
    write(fixture, 'packages/a/b/tests/big.spec.ts', longFunction('specBig', 151))
    write(fixture, 'packages/a/b/src/helper.test.ts', longFunction('testBig', 151))
    const report = reportStructure(fixture)
    expect(report.testFiles).toBe(2)
    expect(report.longFunctions.map(entry => entry.name)).toEqual(['big'])
  })

  it('keeps a generated large file out of the debt list and reports it apart', () => {
    const fixture = fixtureRoot()
    write(fixture, 'packages/a/b/src/large.ts', filler(801, false))
    write(fixture, 'packages/a/b/src/catalog.ts', filler(801, true))
    const report = reportStructure(fixture)
    expect(report.largeFiles).toEqual([{ path: 'packages/a/b/src/large.ts', lines: 801 }])
    expect(report.generatedFiles).toBe(1)
    expect(report.generatedLargeFiles).toEqual([{ path: 'packages/a/b/src/catalog.ts', lines: 801 }])
  })

  // The glob admits a name the read cannot resolve, which is the state a
  // concurrent spec leaves behind when it removes a probe file under this tree
  // between the listing and the read. A symlink reproduces it deterministically;
  // Windows withholds that privilege by default.
  it.skipIf(process.platform === 'win32')('skips a corpus entry that vanishes before its read', () => {
    const fixture = fixtureRoot()
    write(fixture, 'packages/a/b/src/kept.ts', longFunction('kept', 151))
    symlinkSync('absent.ts', join(fixture, 'packages/a/b/src/vanished.ts'))
    const report = reportStructure(fixture)
    expect(report.longFunctions.map(entry => entry.name)).toEqual(['kept'])
    expect(report.scanned).toBe(2)
  })

  it('reports the shipped sources with the ledger figures recoverable', () => {
    const report = reportStructure(root)
    expect(report.scanned).toBeGreaterThan(0)
    expect(report.longFunctions.length).toBeGreaterThan(0)
    expect(report.largeFiles.length).toBeGreaterThan(0)
    expect(report.longFunctions[0]?.lines).toBeGreaterThanOrEqual(report.longFunctions.at(-1)?.lines ?? 0)
    expect(report.largeFiles[0]?.lines).toBeGreaterThanOrEqual(report.largeFiles.at(-1)?.lines ?? 0)
  })
})
