/**
 * Read-only structural-debt report.
 *
 * Counts the two figures `docs/TECH_DEBT.md` tracks under "结构债": function
 * declarations longer than 150 lines and non-generated source files longer
 * than 800 lines, measured over the shipped `packages` sources with the
 * TypeScript AST. A function's length is its declaration span, first line
 * through closing brace, so a multi-line parameter list counts. Test files and
 * generated files are reported separately and excluded from the debt counts.
 * The command never fails on a count: it exists so the ledger's numbers and its
 * largest-file list can be recomputed with one command.
 *
 * Run `pnpm run report:structure` for the counts, and
 * `pnpm run report:structure -- --top 20` to print the largest entries.
 * @module scripts/report-structure
 */

import { globSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import ts from 'typescript'

const ROOT = resolve(import.meta.dirname, '..')

/** Roots of the scanned corpus, matching the ledger's `packages/<group>/<pkg>/src` scope. */
const CORPUS_ROOTS: readonly string[] = ['packages']

/** Function-declaration line count above which a declaration is structural debt. */
const LONG_FUNCTION_LINES = 150

/** Source-file line count above which a file is structural debt. */
const LARGE_FILE_LINES = 800

/** One oversized function declaration. */
export interface LongFunction {
  /** Repository-relative path. */
  readonly path: string
  /** 1-based line of the function's declaration. */
  readonly line: number
  /** Function name, or `<anonymous>` for a declaration with no name. */
  readonly name: string
  /** Line count of the declaration, first line through closing brace. */
  readonly lines: number
}

/** The report. */
export interface StructureReport {
  /** Files parsed. */
  readonly scanned: number
  /** Test files skipped. */
  readonly testFiles: number
  /** Generated files whose size is reported but not counted as debt. */
  readonly generatedFiles: number
  /** Function declarations over the threshold, longest first. */
  readonly longFunctions: readonly LongFunction[]
  /** Non-generated source files over the threshold, largest first. */
  readonly largeFiles: readonly { readonly path: string; readonly lines: number }[]
  /** Generated source files over the threshold, reported apart. */
  readonly generatedLargeFiles: readonly { readonly path: string; readonly lines: number }[]
}

/** Whether a path is a test file. */
function isTestFile(path: string): boolean {
  return /\/tests?\//u.test(path) || /\.(?:spec|test)\.(?:ts|tsx)$/u.test(path)
}

/** Whether a file declares itself generated in its opening comment. */
function isGeneratedFile(source: string): boolean {
  return source.split('\n', 5).some(line => line.includes('Generated by'))
}

/** Line count of a text, ignoring a single trailing newline. */
function lineCount(source: string): number {
  return source.split('\n').length - (source.endsWith('\n') ? 1 : 0)
}

/** 1-based line of a position. */
function lineOf(source: ts.SourceFile, position: number): number {
  return source.getLineAndCharacterOfPosition(position).line + 1
}

/** Every function-like node the AST walk admits. */
function functionLike(node: ts.Node): node is ts.FunctionLikeDeclaration {
  return ts.isFunctionDeclaration(node)
    || ts.isFunctionExpression(node)
    || ts.isArrowFunction(node)
    || ts.isMethodDeclaration(node)
    || ts.isConstructorDeclaration(node)
    || ts.isGetAccessorDeclaration(node)
    || ts.isSetAccessorDeclaration(node)
}

/**
 * Read one corpus entry, or null when it disappeared before the read.
 *
 * The scan lists the corpus first and reads it after, and specs run beside this
 * one that write transient probe files under `packages/<group>/<pkg>/src` (see
 * `oxlint-contract.spec.ts`), so an entry the glob admitted can be gone by the
 * time it is read. It is absent from this point-in-time report rather than an
 * error; every other read failure still propagates.
 * @param root - repository root.
 * @param path - repository-relative entry the glob admitted.
 * @returns the file's text, or null when the entry no longer exists.
 */
function readCorpusEntry(root: string, path: string): string | null {
  try {
    return readFileSync(resolve(root, path), 'utf8')
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return null
    throw error
  }
}

/**
 * Measure the structural-debt figures.
 * @param root - repository root.
 * @returns the report.
 */
export function reportStructure(root: string): StructureReport {
  const scanned = globSync([...CORPUS_ROOTS.map(base => `${base}/**/*.{ts,tsx}`)], { cwd: root })
    .filter(path => !path.includes('/node_modules/') && !path.includes('/lib/') && !path.includes('/dist/'))
    .sort()
  const longFunctions: LongFunction[] = []
  const largeFiles: { path: string; lines: number }[] = []
  const generatedLargeFiles: { path: string; lines: number }[] = []
  let testFiles = 0
  let generatedFiles = 0
  for (const path of scanned) {
    if (isTestFile(path)) {
      testFiles += 1
      continue
    }
    const text = readCorpusEntry(root, path)
    if (text === null) continue
    if (isGeneratedFile(text)) {
      generatedFiles += 1
      if (lineCount(text) > LARGE_FILE_LINES) generatedLargeFiles.push({ path, lines: lineCount(text) })
      continue
    }
    const lines = lineCount(text)
    if (lines > LARGE_FILE_LINES) largeFiles.push({ path, lines })
    const source = ts.createSourceFile(
      path, text, ts.ScriptTarget.Latest, true,
      path.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
    )
    const visit = (node: ts.Node): void => {
      if (functionLike(node) && node.body !== undefined && ts.isBlock(node.body)) {
        const lines = lineOf(source, node.getEnd()) - lineOf(source, node.getStart(source)) + 1
        if (lines > LONG_FUNCTION_LINES) {
          longFunctions.push({
            path,
            line: lineOf(source, node.getStart(source)),
            name: node.name?.getText(source) ?? '<anonymous>',
            lines,
          })
        }
      }
      ts.forEachChild(node, visit)
    }
    visit(source)
  }
  longFunctions.sort((left, right) => right.lines - left.lines)
  largeFiles.sort((left, right) => right.lines - left.lines)
  generatedLargeFiles.sort((left, right) => right.lines - left.lines)
  return { scanned: scanned.length, testFiles, generatedFiles, longFunctions, largeFiles, generatedLargeFiles }
}

if (process.argv[1] !== undefined && import.meta.filename === resolve(process.argv[1])) {
  const report = reportStructure(ROOT)
  const topIndex = process.argv.indexOf('--top')
  const top = topIndex === -1 ? 0 : Number.parseInt(process.argv[topIndex + 1] ?? '10', 10)
  process.stdout.write(
    `report-structure: ${String(report.scanned)} file(s) scanned (${String(report.testFiles)} test, `
    + `${String(report.generatedFiles)} generated); ${String(report.longFunctions.length)} function(s) > ${String(LONG_FUNCTION_LINES)} lines; `
    + `${String(report.largeFiles.length)} source file(s) > ${String(LARGE_FILE_LINES)} lines `
    + `(${String(report.generatedLargeFiles.length)} generated over the same size reported apart).\n`,
  )
  if (top > 0) {
    process.stdout.write('Largest functions:\n')
    for (const entry of report.longFunctions.slice(0, top)) {
      process.stdout.write(`  ${String(entry.lines).padStart(5)}  ${entry.path}:${String(entry.line)}  ${entry.name}\n`)
    }
    process.stdout.write('Largest source files:\n')
    for (const entry of report.largeFiles.slice(0, top)) {
      process.stdout.write(`  ${String(entry.lines).padStart(5)}  ${entry.path}\n`)
    }
  }
}
